name: Continuous Integration

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  unit-tests:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.9, 3.11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run type check
        run: |
          mypy --install-types deepinfra --non-interactive --verbose

      - name: Run lint check
        run: |
          black --check --verbose deepinfra